const STORE="noir-cafe-menu-v1", CART="noir-cafe-cart-v1", AUTH="noir-cafe-admin-auth";
const SUPABASE_URL="https://nphenccoyaqkmusaknxp.supabase.co";
const SUPABASE_KEY="sb_publishable_mrfc6H6GVYdmQgZ2IC5uww_XgSCw_8c";
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const ADMIN_EMAIL="admin@testt.local";
const ADMIN={username:"admin",password:"753248619"};
const FALLBACK={
hot:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=75",
cold:"https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=75",
food:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=75",
hookah:"https://images.unsplash.com/photo-1528495612343-9ca9f4a4de28?auto=format&fit=crop&w=900&q=75",
dessert:"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=75"};
const defaults={
settings:{cafeName:"NOIR Café",menuTitle:"یک شب خوب،\nبا انتخاب درست.",menuSubtitle:"قهوه‌ی دقیق، طعم‌های جسور و فضای آرام؛ منوی خود را انتخاب کنید.",phone:"۰۹۰۰ ۰۰۰ ۰۰۰۰",address:"آدرس کافه را از پنل مدیریت وارد کنید",instagram:"@noircafe",openingHours:"هر روز ۱۰:۰۰ تا ۲۳:۳۰",currency:"تومان"},
categories:[
{id:"hot",name:"نوشیدنی گرم",description:"قهوه و نوشیدنی‌های گرم دقیق و آرامش‌بخش",icon:"☕",visible:true,sortOrder:1},
{id:"cold",name:"نوشیدنی سرد",description:"بار سرد، موکتل و انتخاب‌های خنک",icon:"◌",visible:true,sortOrder:2},
{id:"food",name:"فست فود",description:"غذاهای سریع با اجرای پریمیوم",icon:"◈",visible:true,sortOrder:3},
{id:"hookah",name:"قلیان",description:"بلندینگ‌های کلاسیک و اختصاصی",icon:"◐",visible:true,sortOrder:4},
{id:"dessert",name:"دسر",description:"انتخاب‌های شیرین برای پایان خوب",icon:"◇",visible:true,sortOrder:5}],
products:[
{id:"p1",name:"اسپرسو",categoryId:"hot",description:"شات کوتاه و متعادل با کرمای غلیظ.",ingredients:["قهوه ۱۰۰٪","کرما"],price:85000,discountPrice:null,image:"https://images.unsplash.com/photo-1510707577719-ae7c14805e32?auto=format&fit=crop&w=900&q=80",available:true,popular:true,signature:false,badge:"محبوب",sizes:[],addons:[],sortOrder:1},
{id:"p2",name:"کاپوچینو",categoryId:"hot",description:"اسپرسو، شیر بافت‌داده و فوم لطیف.",ingredients:["اسپرسو","شیر","فوم شیر"],price:145000,discountPrice:null,image:"https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=900&q=80",available:true,popular:false,signature:true,badge:"Signature",sizes:["Regular","Large"],addons:[],sortOrder:2},
{id:"p3",name:"لاته",categoryId:"hot",description:"بادی نرم و شیری با پایان متعادل.",ingredients:["اسپرسو","شیر"],price:155000,discountPrice:null,image:"https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=900&q=80",available:true,popular:true,signature:false,badge:"پرفروش",sizes:["Regular","Large"],addons:["شات اضافه","سیروپ وانیل"],sortOrder:3},
{id:"p4",name:"آیس لاته",categoryId:"cold",description:"لاته‌ی سرد، خنک و مینیمال.",ingredients:["اسپرسو","شیر","یخ"],price:175000,discountPrice:null,image:"https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80",available:true,popular:true,signature:false,badge:"Popular",sizes:["Regular","Large"],addons:["شات اضافه"],sortOrder:1},
{id:"p5",name:"موهیتو لیمو و نعناع",categoryId:"cold",description:"ترش و خنک با نعناع تازه و لیموی تازه.",ingredients:["لیمو","نعناع","سودا","یخ"],price:185000,discountPrice:null,image:"https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=900&q=80",available:true,popular:false,signature:true,badge:"Signature",sizes:["Regular","Large"],addons:[],sortOrder:2},
{id:"p6",name:"میلک‌شیک شکلات",categoryId:"cold",description:"بافت غلیظ، شکلاتی و مناسب اشتراک‌گذاری.",ingredients:["شیر","بستنی","شکلات"],price:220000,discountPrice:null,image:"https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=900&q=80",available:true,popular:false,signature:false,badge:"جدید",sizes:["Regular","Large"],addons:["خامه"],sortOrder:3},
{id:"p7",name:"Noir Burger",categoryId:"food",description:"برگر دست‌ساز با پنیر، پیاز کاراملی و سس اختصاصی.",ingredients:["گوشت","پنیر","پیاز کاراملی","سس Noir"],price:385000,discountPrice:345000,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",available:true,popular:true,signature:true,badge:"Signature",sizes:["Single","Double"],addons:["پنیر اضافه","سیب‌زمینی"],sortOrder:1},
{id:"p8",name:"Crispy Chicken",categoryId:"food",description:"مرغ سوخاری ترد با سس مخصوص و سیب‌زمینی.",ingredients:["مرغ","پانکو","سس مخصوص"],price:330000,discountPrice:null,image:"https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=900&q=80",available:true,popular:true,signature:false,badge:"پرفروش",sizes:[],addons:["سس اضافه"],sortOrder:2},
{id:"p9",name:"Loaded Fries",categoryId:"food",description:"سیب‌زمینی ترد با پنیر، گوشت و سس‌های خانه.",ingredients:["سیب‌زمینی","پنیر","گوشت","سس"],price:245000,discountPrice:null,image:"https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80",available:true,popular:false,signature:false,badge:"جدید",sizes:[],addons:[],sortOrder:3},
{id:"p10",name:"Classic Mint",categoryId:"hookah",description:"بلندینگ کلاسیک نعناع با حس خنک و تمیز.",ingredients:["نعناع","بلندینگ کلاسیک"],price:420000,discountPrice:null,image:"https://images.unsplash.com/photo-1528502668750-88ba58015b2d?auto=format&fit=crop&w=900&q=80",available:true,popular:true,signature:false,badge:"محبوب",sizes:[],addons:[],sortOrder:1},
{id:"p11",name:"Fruit Blend",categoryId:"hookah",description:"ترکیب میوه‌ای متعادل برای یک انتخاب متفاوت.",ingredients:["بلندینگ میوه‌ای"],price:480000,discountPrice:null,image:"https://images.unsplash.com/photo-1528495612343-9ca9f4a4de28?auto=format&fit=crop&w=900&q=80",available:true,popular:false,signature:true,badge:"Signature",sizes:[],addons:[],sortOrder:2},
{id:"p12",name:"تیرامیسو",categoryId:"dessert",description:"لایه‌های ماسکارپونه، قهوه و کاکائو.",ingredients:["ماسکارپونه","قهوه","کاکائو"],price:190000,discountPrice:null,image:"https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=80",available:true,popular:true,signature:false,badge:"محبوب",sizes:[],addons:[],sortOrder:1},
{id:"p13",name:"چیزکیک سن‌سباستین",categoryId:"dessert",description:"بافت کرمی و سطح کاراملی‌شده.",ingredients:["پنیر خامه‌ای","خامه","وانیل"],price:210000,discountPrice:null,image:"https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=80",available:true,popular:false,signature:true,badge:"Signature",sizes:[],addons:[],sortOrder:2}
]};
let data=loadData(),cart=loadCart(),current=null,qty=1,adminTab="overview",selectedVariants={sizes:null,addons:null};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const num=n=>new Intl.NumberFormat("fa-IR").format(Number(n)||0);
const money=n=>num(n)+" "+(data.settings.currency||"تومان");
const uid=p=>p+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,7);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fallback=c=>FALLBACK[c]||FALLBACK.hot;
function loadData(){try{const x=JSON.parse(localStorage.getItem(STORE));if(x?.products)return x}catch(e){}return JSON.parse(JSON.stringify(defaults))}
function loadCart(){try{return JSON.parse(localStorage.getItem(CART))||[]}catch(e){return[]}}
function save(){localStorage.setItem(STORE,JSON.stringify(data))}
function saveCart(){localStorage.setItem(CART,JSON.stringify(cart))}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove("show"),2100)}
function closeOverlay(id){$("#"+id).hidden=true}
function card(p){return '<article class="product-card" data-id="'+esc(p.id)+'">'+(p.badge?'<span class="badge">'+esc(p.badge)+"</span>":"")+'<div class="product-image"><img loading="lazy" decoding="async" src="'+esc(p.image||fallback(p.categoryId))+'" alt="'+esc(p.name)+'" onerror="this.onerror=null;this.src=\''+fallback(p.categoryId)+'\'"></div><div class="product-body"><div class="product-top"><h4 class="product-name">'+esc(p.name)+'</h4><span class="price">'+money(p.discountPrice??p.price)+'</span></div><p class="product-desc">'+esc(p.description||"")+'</p>'+(p.discountPrice?'<span class="old-price">'+money(p.price)+'</span>':"")+'<button class="quick-add" data-quick="'+esc(p.id)+'">افزودن سریع</button></div></article>'}
function render(){
  $$("[data-setting]").forEach(e=>{const k=e.dataset.setting;e.textContent=data.settings[k]||""});
  const title=$("[data-setting='menuTitle']");if(title)title.innerHTML=esc(data.settings.menuTitle||"").replace(/\n/g,"<br>");
  $$("[data-setting-link]").forEach(e=>{const k=e.dataset.settingLink,v=data.settings[k]||"";e.textContent=v;e.href=k==="phone"?"tel:"+v.replace(/[^+\d]/g,""):v.startsWith("http")?v:"https://instagram.com/"+v.replace("@","")});
  const cats=data.categories.filter(c=>c.visible!==false).sort((a,b)=>a.sortOrder-b.sortOrder);
  $("#categoryNav").innerHTML=cats.map((c,i)=>'<button class="cat-btn '+(i===0?"active":"")+'" data-cat="'+esc(c.id)+'">'+esc(c.name)+'</button>').join("");
  $("#menuSections").innerHTML=cats.map(c=>{const ps=data.products.filter(p=>p.categoryId===c.id&&p.available).sort((a,b)=>a.sortOrder-b.sortOrder);if(!ps.length)return"";return'<section class="menu-category" id="cat-'+esc(c.id)+'"><div class="category-title"><div><p class="eyebrow">'+esc(c.icon||"")+'</p><h3>'+esc(c.name)+'</h3></div><p>'+esc(c.description||"")+'</p></div><div class="product-grid">'+ps.map(card).join("")+'</div></section>'}).join("")||'<div class="empty-state"><span>◌</span><h4>منو خالی است</h4><p>از پنل مدیریت محصولات را اضافه کنید.</p></div>';
  const sig=data.products.filter(p=>p.signature&&p.available);if(sig.length){$("#categoryNav").insertAdjacentHTML("afterbegin",'<button class="cat-btn" data-cat="signature">Signature</button>');$("#menuSections").insertAdjacentHTML("afterbegin",'<section class="signature-wrap menu-category" id="cat-signature"><div class="category-title"><div><p class="eyebrow">CURATED BY NOIR</p><h3>Signature</h3></div><p>انتخاب‌های امضای کافه</p></div><div class="product-grid">'+sig.map(card).join("")+'</div></section>');}
  $(".cat-btn").forEach(b=>b.onclick=()=>$("#cat-"+b.dataset.cat)?.scrollIntoView({behavior:"smooth"}));
  $$(".product-card").forEach(c=>c.onclick=e=>{if(e.target.closest(".quick-add")){add(c.dataset.id);return}openProduct(c.dataset.id)});
}
function openProduct(id){
  const p=data.products.find(x=>x.id===id);if(!p)return;current=p;qty=1;selectedVariants={sizes:p.sizes?.[0]||null,addons:p.addons?.[0]||null};$("#modalQty").textContent="۱";
  $("#modalImage").src=p.image||fallback(p.categoryId);$("#modalImage").alt=p.name;$("#modalImage").onerror=()=>$("#modalImage").src=fallback(p.categoryId);
  $("#modalCategory").textContent=(data.categories.find(c=>c.id===p.categoryId)||{}).name||"MENU";$("#modalName").textContent=p.name;$("#modalDescription").textContent=p.description||"";
  $("#modalIngredients").innerHTML=(p.ingredients||[]).map(x=>'<span class="ingredient">'+esc(x)+"</span>").join("");
  $("#modalPrice").innerHTML=money(p.discountPrice??p.price)+(p.discountPrice?' <span class="old-price">'+money(p.price)+"</span>":"");
  variants("modalSizes","سایز",p.sizes);variants("modalAddons","افزودنی",p.addons);$("#productOverlay").hidden=false;
}
function variants(id,label,arr){const w=$("#"+id);if(!arr?.length){w.innerHTML="";return}const key=id==="modalSizes"?"sizes":"addons";w.innerHTML='<span class="variant-label">'+label+'</span><div class="variant-options">'+arr.map((x,i)=>'<button type="button" class="variant-option '+(i===0?"selected":"")+'" data-variant="'+esc(x)+'">'+esc(x)+"</button>").join("")+"</div>";Array.from(w.querySelectorAll(".variant-option")).forEach(b=>b.onclick=()=>{Array.from(w.querySelectorAll(".variant-option")).forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedVariants[key]=b.dataset.variant})}
function add(id,n=1,options=null){const p=data.products.find(x=>x.id===id);if(!p||!p.available)return toast("این آیتم موجود نیست");const opts=options||{};const x=cart.find(i=>i.productId===id&&JSON.stringify(i.options||{})===JSON.stringify(opts));if(x)x.qty+=n;else cart.push({id:uid("cart"),productId:id,qty:n,options:opts});saveCart();renderCart();toast(p.name+" به سبد اضافه شد")}
function renderCart(){const items=cart.map(i=>({i,p:data.products.find(p=>p.id===i.productId)})).filter(x=>x.p);$("#cartCount").textContent=num(items.reduce((a,x)=>a+x.i.qty,0));$("#cartItems").innerHTML=items.map(x=>'<div class="cart-item"><img src="'+esc(x.p.image||fallback(x.p.categoryId))+'" alt="'+esc(x.p.name)+'" loading="lazy" decoding="async"><div><h4>'+esc(x.p.name)+'</h4>'+(x.i.options&&(x.i.options.sizes||x.i.options.addons)?'<small class="cart-options">'+esc([x.i.options.sizes,x.i.options.addons].filter(Boolean).join(" · "))+'</small>':"")+'<p>'+money((x.p.discountPrice??x.p.price)*x.i.qty)+'</p><div class="qty"><button data-minus="'+x.i.id+'">−</button><b>'+num(x.i.qty)+'</b><button data-plus="'+x.i.id+'">+</button></div></div><button class="close-btn" data-remove="'+x.i.id+'">×</button></div>').join("");$("#cartEmpty").style.display=items.length?"none":"block";$("#cartFooter").style.display=items.length?"block":"none";$("#cartTotal").textContent=money(items.reduce((a,x)=>a+(x.p.discountPrice??x.p.price)*x.i.qty,0));$$("[data-minus]").forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));$$("[data-plus]").forEach(b=>b.onclick=()=>change(b.dataset.plus,1));$$("[data-remove]").forEach(b=>b.onclick=()=>{cart=cart.filter(i=>i.id!==b.dataset.remove);saveCart();renderCart()})}
function change(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);saveCart();renderCart()}
function toggleCart(v){$("#cartDrawer").classList.toggle("open",v);$("#cartDrawer").setAttribute("aria-hidden",String(!v));document.body.classList.toggle("no-scroll",v)}
function search(q){q=q.trim().toLowerCase();if(!q){$("#searchResults").innerHTML='<div class="empty-state"><span>⌕</span><h4>جستجو در منو</h4><p>نام، مواد اولیه یا توضیحات را وارد کنید.</p></div>';return}const r=data.products.filter(p=>p.available&&(p.name+" "+p.description+" "+(p.ingredients||[]).join(" ")+" "+((data.categories.find(c=>c.id===p.categoryId)||{}).name||"")).toLowerCase().includes(q));$("#searchResults").innerHTML=r.length?r.map(p=>'<button class="search-result" data-result="'+esc(p.id)+'" aria-label="مشاهده '+esc(p.name)+'"><img loading="lazy" decoding="async" src="'+esc(p.image||fallback(p.categoryId))+'" alt="'+esc(p.name)+'"><span><h4>'+esc(p.name)+'</h4><p>'+esc(p.description)+'</p></span><strong class="price">'+money(p.discountPrice??p.price)+"</strong></button>").join(""):'<div class="empty-state"><span>⌕</span><h4>نتیجه‌ای پیدا نشد</h4><p>عبارت دیگری را امتحان کنید.</p></div>';$$("[data-result]").forEach(b=>b.onclick=()=>{closeOverlay("searchOverlay");openProduct(b.dataset.result)})}
function openSearch(){$("#searchOverlay").hidden=false;search($("#searchInput").value);setTimeout(()=>$("#searchInput").focus(),40)}
function adminNav(t,n){return'<button data-tab="'+t+'" class="'+(adminTab===t?"active":"")+'">◈ &nbsp; '+n+"</button>"}
function openAdmin(){ $("#adminApp").hidden=false;document.body.classList.add("no-scroll");if(sessionStorage.getItem(AUTH)==="1")dashboard();else{$("#adminLogin").hidden=false;$("#adminDashboard").hidden=true}}
function dashboard(){ $("#adminLogin").hidden=true;$("#adminDashboard").hidden=false;const active=data.products.filter(p=>p.available).length;$("#adminDashboard").innerHTML='<div class="admin-shell"><aside class="admin-sidebar" id="adminSidebar"><div class="admin-logo">NOIR <span>ADMIN</span></div><nav class="admin-nav">'+adminNav("overview","داشبورد")+adminNav("products","محصولات")+adminNav("categories","دسته‌بندی‌ها")+adminNav("settings","تنظیمات")+'</nav><button class="admin-logout" id="logout">خروج</button></aside><main class="admin-main"><div class="admin-topbar"><div><button class="small-btn mobile-admin-menu" id="adminMenu">☰ منو</button><h1>پنل مدیریت</h1></div><button class="small-btn" id="back">مشاهده منو ↗</button></div><div id="adminView"></div></main></div>';$("#logout").onclick=logout;$("#back").onclick=closeAdmin;$("#adminMenu").onclick=()=>$("#adminSidebar").classList.toggle("mobile-open");$$("[data-tab]").forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;drawAdmin()});drawAdmin()}
function logout(){sessionStorage.removeItem(AUTH);closeAdmin()}
function closeAdmin(){$("#adminApp").hidden=true;document.body.classList.remove("no-scroll")}
function drawAdmin(){const v=$("#adminView");if(adminTab==="overview")v.innerHTML=overview();if(adminTab==="products")v.innerHTML=products();if(adminTab==="categories")v.innerHTML=categories();if(adminTab==="settings")v.innerHTML=settings();bindAdmin()}
function overview(){return'<div class="stats"><div class="stat-card"><span>کل محصولات</span><strong>'+num(data.products.length)+'</strong></div><div class="stat-card"><span>فعال</span><strong>'+num(data.products.filter(p=>p.available).length)+'</strong></div><div class="stat-card"><span>ناموجود</span><strong>'+num(data.products.filter(p=>!p.available).length)+'</strong></div><div class="stat-card"><span>Signature</span><strong>'+num(data.products.filter(p=>p.signature).length)+'</strong></div></div><div class="admin-toolbar"><h2>دسته‌ها</h2><button class="small-btn gold" data-tab="products">مدیریت محصولات</button></div><div class="admin-category-list">'+data.categories.sort((a,b)=>a.sortOrder-b.sortOrder).map(c=>'<div class="admin-category-item"><div class="left"><span>'+esc(c.icon||"◇")+'</span><div><b>'+esc(c.name)+'</b><small style="display:block;color:#666">'+num(data.products.filter(p=>p.categoryId===c.id).length)+' محصول</small></div></div><span class="status-dot '+(c.visible?"":"off")+'"></span></div>').join("")+"</div>"}
function products(){return'<div class="admin-toolbar"><h2>محصولات</h2><button class="small-btn gold" id="newProduct">+ افزودن</button></div><table class="admin-table"><thead><tr><th>محصول</th><th>دسته</th><th>قیمت</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>'+data.products.sort((a,b)=>a.sortOrder-b.sortOrder).map(p=>'<tr><td><div class="admin-product"><img src="'+esc(p.image||fallback(p.categoryId))+'" alt=""><span>'+esc(p.name)+'</span></div></td><td>'+esc((data.categories.find(c=>c.id===p.categoryId)||{}).name||"—")+'</td><td>'+money(p.discountPrice??p.price)+'</td><td><span class="status-dot '+(p.available?"":"off")+'"></span>'+ (p.available?"فعال":"مخفی")+'</td><td><button class="small-btn" data-edit="'+p.id+'">ویرایش</button> <button class="small-btn" data-toggle="'+p.id+'">'+(p.available?"مخفی":"فعال")+'</button> <button class="small-btn" data-delete="'+p.id+'">حذف</button></td></tr>').join("")+"</tbody></table>"}
function categories(){return'<div class="admin-toolbar"><h2>دسته‌بندی‌ها</h2><button class="small-btn gold" id="newCategory">+ افزودن</button></div><div class="admin-category-list">'+data.categories.sort((a,b)=>a.sortOrder-b.sortOrder).map(c=>'<div class="admin-category-item"><div class="left"><span>'+esc(c.icon||"◇")+'</span><div><b>'+esc(c.name)+'</b><small style="display:block;color:#666">'+esc(c.description||"")+'</small></div></div><div><button class="small-btn" data-cat-edit="'+c.id+'">ویرایش</button> <button class="small-btn" data-cat-toggle="'+c.id+'">'+(c.visible?"مخفی":"نمایش")+'</button></div></div>').join("")+"</div>"}
function settings(){const s=data.settings;return'<div class="admin-toolbar"><h2>تنظیمات کافه</h2><button class="small-btn gold" id="saveSettings">ذخیره</button></div><form class="admin-form" id="settingsForm"><div class="form-two"><label>نام کافه<input name="cafeName" value="'+esc(s.cafeName)+'"></label><label>عنوان منو<input name="menuTitle" value="'+esc(s.menuTitle)+'"></label></div><label>زیرعنوان<textarea name="menuSubtitle">'+esc(s.menuSubtitle)+'</textarea></label><div class="form-two"><label>شماره تماس<input name="phone" value="'+esc(s.phone)+'"></label><label>اینستاگرام<input name="instagram" value="'+esc(s.instagram)+'"></label></div><div class="form-two"><label>ساعت کاری<input name="openingHours" value="'+esc(s.openingHours)+'"></label><label>واحد قیمت<input name="currency" value="'+esc(s.currency)+'"></label></div><label>آدرس<input name="address" value="'+esc(s.address)+'"></label><p style="color:#666;font-size:10px">داده‌ها فقط در localStorage همین مرورگر ذخیره می‌شوند.</p></form>'}
function formProduct(id){const old=id?data.products.find(p=>p.id===id):null;const p=old||{name:"",categoryId:data.categories[0]?.id||"",description:"",price:0,discountPrice:"",image:"",ingredients:[],badge:"",sizes:[],addons:[],available:true,popular:false,signature:false,sortOrder:data.products.length+1};$("#adminView").innerHTML='<div class="admin-toolbar"><h2>'+(id?"ویرایش محصول":"محصول جدید")+'</h2><button class="small-btn" id="cancel">بازگشت</button></div><form class="admin-form" id="productForm"><div class="form-two"><label>نام *<input name="name" required value="'+esc(p.name)+'"></label><label>دسته<select name="categoryId">'+data.categories.map(c=>'<option value="'+c.id+'" '+(c.id===p.categoryId?"selected":"")+'>'+esc(c.name)+"</option>").join("")+'</select></label></div><label>توضیحات<textarea name="description">'+esc(p.description)+'</textarea></label><div class="form-two"><label>قیمت<input name="price" type="number" min="0" value="'+p.price+'" required></label><label>قیمت تخفیف<input name="discountPrice" type="number" min="0" value="'+(p.discountPrice??"")+'"></label></div><label>URL تصویر<input name="image" value="'+esc(p.image||"")+'"></label><div class="form-two"><label>مواد اولیه<input name="ingredients" value="'+esc((p.ingredients||[]).join(", "))+'"></label><label>برچسب<input name="badge" value="'+esc(p.badge||"")+'"></label></div><div class="form-two"><label>سایزها<input name="sizes" value="'+esc((p.sizes||[]).join(", "))+'"></label><label>افزودنی‌ها<input name="addons" value="'+esc((p.addons||[]).join(", "))+'"></label></div><label>ترتیب<input name="sortOrder" type="number" value="'+(p.sortOrder||1)+'"></label><div class="check-row"><label><input name="available" type="checkbox" '+(p.available?"checked":"")+'> موجود</label><label><input name="popular" type="checkbox" '+(p.popular?"checked":"")+'> محبوب</label><label><input name="signature" type="checkbox" '+(p.signature?"checked":"")+'> Signature</label></div><div class="admin-form-actions"><button class="primary-btn" type="submit">ذخیره</button></div></form>';$("#cancel").onclick=drawAdmin;$("#productForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),x={id:p.id||uid("p"),name:f.get("name").trim(),categoryId:f.get("categoryId"),description:f.get("description").trim(),price:+f.get("price")||0,discountPrice:f.get("discountPrice")?+f.get("discountPrice"):null,image:f.get("image").trim(),ingredients:list(f.get("ingredients")),badge:f.get("badge").trim(),sizes:list(f.get("sizes")),addons:list(f.get("addons")),available:f.has("available"),popular:f.has("popular"),signature:f.has("signature"),sortOrder:+f.get("sortOrder")||1};if(old)data.products=data.products.map(q=>q.id===old.id?x:q);else data.products.push(x);save();render();adminTab="products";dashboard();toast("محصول ذخیره شد")}}
function list(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
function formCategory(id){const old=id?data.categories.find(c=>c.id===id):null,c=old||{name:"",description:"",icon:"◇",visible:true,sortOrder:data.categories.length+1};$("#adminView").innerHTML='<div class="admin-toolbar"><h2>'+(id?"ویرایش دسته":"دسته جدید")+'</h2><button class="small-btn" id="cancel">بازگشت</button></div><form class="admin-form" id="categoryForm"><div class="form-two"><label>نام *<input name="name" required value="'+esc(c.name)+'"></label><label>آیکون<input name="icon" value="'+esc(c.icon||"◇")+'"></label></div><label>توضیحات<textarea name="description">'+esc(c.description||"")+'</textarea></label><label>ترتیب<input name="sortOrder" type="number" value="'+c.sortOrder+'"></label><label><input name="visible" type="checkbox" '+(c.visible?"checked":"")+'> نمایش</label><button class="primary-btn" type="submit">ذخیره</button></form>';$("#cancel").onclick=drawAdmin;$("#categoryForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),x={id:c.id||uid("cat"),name:f.get("name").trim(),description:f.get("description").trim(),icon:f.get("icon").trim()||"◇",sortOrder:+f.get("sortOrder")||1,visible:f.has("visible")};if(old)data.categories=data.categories.map(q=>q.id===old.id?x:q);else data.categories.push(x);save();render();adminTab="categories";dashboard();toast("دسته ذخیره شد")}}
function bindAdmin(){
  $$("[data-tab]").forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;drawAdmin()});
  $("#newProduct")?.addEventListener("click",()=>formProduct());$("#newCategory")?.addEventListener("click",()=>formCategory());
  $$("[data-edit]").forEach(b=>b.onclick=()=>formProduct(b.dataset.edit));$$("[data-cat-edit]").forEach(b=>b.onclick=()=>formCategory(b.dataset.catEdit));
  $$("[data-toggle]").forEach(b=>b.onclick=()=>{const p=data.products.find(x=>x.id===b.dataset.toggle);p.available=!p.available;save();render();drawAdmin()});
  $$("[data-cat-toggle]").forEach(b=>b.onclick=()=>{const c=data.categories.find(x=>x.id===b.dataset.catToggle);c.visible=!c.visible;save();render();drawAdmin()});
  $$("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("این محصول حذف شود؟")){data.products=data.products.filter(p=>p.id!==b.dataset.delete);save();render();drawAdmin()}});$("#saveSettings")?.addEventListener("click",()=>{const f=new FormData($("#settingsForm"));Object.keys(data.settings).forEach(k=>{if(f.has(k))data.settings[k]=String(f.get(k)).trim()});save();render();toast("تنظیمات ذخیره شد")})
}
$("#openSearch").onclick=()=>openSearch();$("#openSearch2").onclick=()=>openSearch();$("#searchInput").oninput=e=>search(e.target.value);$("#clearSearch").onclick=()=>{$("#searchInput").value="";search("")};
$("#openCart").onclick=()=>toggleCart(true);$("#clearCart").onclick=()=>{cart=[];saveCart();renderCart()};$("#checkoutBtn").onclick=()=>{if(cart.length)$("#checkoutOverlay").hidden=false;else toast("سبد خالی است")};
$("#modalMinus").onclick=()=>{qty=Math.max(1,qty-1);$("#modalQty").textContent=num(qty)};$("#modalPlus").onclick=()=>{qty=Math.min(20,qty+1);$("#modalQty").textContent=num(qty)};$("#modalAdd").onclick=()=>{add(current.id,qty,selectedVariants);closeOverlay("productOverlay");toggleCart(true)};
$("#openAdmin").onclick=openAdmin;$("#openAdmin2").onclick=openAdmin;$("#closeAdminLogin").onclick=closeAdmin;$("#loginForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(f.get("username")===ADMIN.username&&f.get("password")===ADMIN.password){sessionStorage.setItem(AUTH,"1");dashboard()}else $("#loginError").textContent="نام کاربری یا رمز عبور صحیح نیست."};
$$("[data-close]").forEach(b=>b.onclick=()=>closeOverlay(b.dataset.close));$$("[data-close-cart]").forEach(b=>b.onclick=()=>toggleCart(false));
$("#checkoutForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),items=cart.map(i=>({i,p:data.products.find(x=>x.id===i.productId)})).filter(x=>x.p),total=items.reduce((a,x)=>a+(x.p.discountPrice??x.p.price)*x.i.qty,0);$("#orderSummary").hidden=false;$("#orderSummary").innerHTML="<h4>خلاصه سفارش</h4><p>مشتری: "+esc(f.get("name"))+" · تماس: "+esc(f.get("phone"))+" · میز: "+esc(f.get("table")||"—")+"</p>"+items.map(x=>'<div class="summary-row"><span>'+esc(x.p.name)+" × "+num(x.i.qty)+'</span><b>'+money((x.p.discountPrice??x.p.price)*x.i.qty)+"</b></div>").join("")+'<div class="summary-row"><strong>جمع کل</strong><strong>'+money(total)+'</strong></div>'+(f.get("note")?'<p class="order-note">یادداشت: '+esc(f.get("note"))+'</p>':"")+'<div class="notice">نسخه فعلی بدون بک‌اند است؛ سفارش به سرور ارسال نشده است.</div>'};
document.addEventListener("keydown",e=>{if(e.key==="Escape"){["searchOverlay","productOverlay","checkoutOverlay"].forEach(closeOverlay);toggleCart(false)}});

function mapDbCategory(c){return{id:String(c.slug),dbId:c.id,name:c.name,description:c.description||"",icon:c.icon||"◇",visible:c.active!==false,sortOrder:Number(c.sort_order)||0,slug:c.slug}}
function mapDbProduct(p){return{id:String(p.id),dbId:p.id,name:p.name,categoryId:String(p.category),description:p.description||"",ingredients:Array.isArray(p.ingredients)?p.ingredients:String(p.ingredients||"").split(",").map(x=>x.trim()).filter(Boolean),price:Number(p.price)||0,discountPrice:p.discount_price==null?null:Number(p.discount_price),image:p.image_url||"",available:p.available!==false&&p.active!==false,popular:p.popular===true,signature:p.signature===true,badge:p.badge||"",sizes:Array.isArray(p.sizes)?p.sizes:[],addons:Array.isArray(p.addons)?p.addons:[],sortOrder:Number(p.sort_order)||0,slug:p.slug}}
async function loadSupabaseData(){
  const [s,c,p]=await Promise.all([
    supabase.from("menu_settings").select("*").eq("id",1).maybeSingle(),
    supabase.from("menu_categories").select("*").order("sort_order",{ascending:true}),
    supabase.from("products").select("*").eq("active",true).order("sort_order",{ascending:true}).order("id",{ascending:true})
  ]);
  if(s.error||c.error||p.error) throw s.error||c.error||p.error;
  if(s.data)data.settings={cafeName:s.data.cafe_name||"Testt Café",menuTitle:s.data.menu_title||"منوی کافه",menuSubtitle:s.data.menu_subtitle||"",phone:s.data.phone||"",address:s.data.address||"",instagram:s.data.instagram||"",openingHours:s.data.opening_hours||"",currency:s.data.currency||"تومان"};
  if(c.data?.length)data.categories=c.data.map(mapDbCategory);
  if(p.data)data.products=p.data.map(mapDbProduct);
}
async function adminSession(){const {data:{session}}=await supabase.auth.getSession();return session&&await isDbAdmin()}
async function isDbAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user?.email)return false;const {data,error}=await supabase.from("admins").select("email").eq("email",user.email).maybeSingle();return !error&&!!data}
async function openAdmin(){ $("#adminApp").hidden=false;document.body.classList.add("no-scroll");$("#loginError").textContent="";if(await adminSession())dashboard();else{$("#adminLogin").hidden=false;$("#adminDashboard").hidden=true}}
async function logout(){await supabase.auth.signOut();sessionStorage.removeItem(AUTH);closeAdmin()}
function settings(){const s=data.settings;return'<div class="admin-toolbar"><h2>تنظیمات کافه</h2><button class="small-btn gold" id="saveSettings">ذخیره</button></div><form class="admin-form" id="settingsForm"><div class="form-two"><label>نام کافه<input name="cafeName" value="'+esc(s.cafeName)+'"></label><label>عنوان منو<input name="menuTitle" value="'+esc(s.menuTitle)+'"></label></div><label>زیرعنوان<textarea name="menuSubtitle">'+esc(s.menuSubtitle)+'</textarea></label><div class="form-two"><label>شماره تماس<input name="phone" value="'+esc(s.phone)+'"></label><label>اینستاگرام<input name="instagram" value="'+esc(s.instagram)+'"></label></div><div class="form-two"><label>ساعت کاری<input name="openingHours" value="'+esc(s.openingHours)+'"></label><label>واحد قیمت<input name="currency" value="'+esc(s.currency)+'</label></div><label>آدرس<input name="address" value="'+esc(s.address)+'"></label><p style="color:#666;font-size:10px">اطلاعات این بخش مستقیماً در Supabase ذخیره می‌شود.</p></form>'}
function formProduct(id){
  const old=id?data.products.find(p=>p.id===id):null,p=old||{name:"",categoryId:data.categories[0]?.id||"",description:"",price:0,discountPrice:"",image:"",ingredients:[],badge:"",sizes:[],addons:[],available:true,popular:false,signature:false,sortOrder:data.products.length+1,slug:""};
  $("#adminView").innerHTML='<div class="admin-toolbar"><h2>'+(id?"ویرایش محصول":"محصول جدید")+'</h2><button class="small-btn" id="cancel">بازگشت</button></div><form class="admin-form" id="productForm"><div class="form-two"><label>نام *<input name="name" required value="'+esc(p.name)+'"></label><label>دسته<select name="categoryId">'+data.categories.map(c=>'<option value="'+esc(c.id)+'" '+(c.id===p.categoryId?"selected":"")+'>'+esc(c.name)+"</option>").join("")+'</select></label></div><label>توضیحات<textarea name="description">'+esc(p.description)+'</textarea></label><div class="form-two"><label>قیمت<input name="price" type="number" min="0" value="'+p.price+'" required></label><label>قیمت تخفیف<input name="discountPrice" type="number" min="0" value="'+(p.discountPrice??"")+'"></label></div><label>URL تصویر<input name="image" value="'+esc(p.image||"")+'"></label><div class="form-two"><label>مواد اولیه<input name="ingredients" value="'+esc((p.ingredients||[]).join(", "))+'"></label><label>برچسب<input name="badge" value="'+esc(p.badge||"")+'"></label></div><div class="form-two"><label>سایزها<input name="sizes" value="'+esc((p.sizes||[]).join(", "))+'"></label><label>افزودنی‌ها<input name="addons" value="'+esc((p.addons||[]).join(", "))+'"></label></div><label>ترتیب<input name="sortOrder" type="number" value="'+(p.sortOrder||1)+'"></label><div class="check-row"><label><input name="available" type="checkbox" '+(p.available?"checked":"")+'> موجود</label><label><input name="popular" type="checkbox" '+(p.popular?"checked":"")+'> محبوب</label><label><input name="signature" type="checkbox" '+(p.signature?"checked":"")+'> Signature</label></div><div class="admin-form-actions"><button class="primary-btn" type="submit">ذخیره</button></div></form>';
  $("#cancel").onclick=drawAdmin;
  $("#productForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),name=String(f.get("name")||"").trim(),payload={name,slug:p.slug||name.toLowerCase().replace(/\\s+/g,"-"),description:String(f.get("description")||"").trim(),price:+f.get("price")||0,discount_price:f.get("discountPrice")?+f.get("discountPrice"):null,category:String(f.get("categoryId")),ingredients:list(f.get("ingredients")).join(", "),image_url:String(f.get("image")||"").trim(),available:f.has("available"),active:f.has("available"),popular:f.has("popular"),signature:f.has("signature"),badge:String(f.get("badge")||"").trim(),sizes:list(f.get("sizes")),addons:list(f.get("addons")),sort_order:+f.get("sortOrder")||1};let r=old?await supabase.from("products").update(payload).eq("id",old.dbId):await supabase.from("products").insert(payload);if(r.error)return toast("ذخیره محصول ناموفق بود: "+r.error.message);await loadSupabaseData();render();adminTab="products";dashboard();toast("محصول ذخیره شد")};
}
function formCategory(id){
  const old=id?data.categories.find(c=>c.id===id):null,c=old||{name:"",description:"",icon:"◇",visible:true,sortOrder:data.categories.length+1,slug:""};
  $("#adminView").innerHTML='<div class="admin-toolbar"><h2>'+(id?"ویرایش دسته":"دسته جدید")+'</h2><button class="small-btn" id="cancel">بازگشت</button></div><form class="admin-form" id="categoryForm"><div class="form-two"><label>نام *<input name="name" required value="'+esc(c.name)+'"></label><label>آیکون<input name="icon" value="'+esc(c.icon||"◇")+'"></label></div><label>توضیحات<textarea name="description">'+esc(c.description||"")+'</textarea></label><label>ترتیب<input name="sortOrder" type="number" value="'+c.sortOrder+'"></label><label><input name="visible" type="checkbox" '+(c.visible?"checked":"")+'> نمایش</label><button class="primary-btn" type="submit">ذخیره</button></form>';
  $("#cancel").onclick=drawAdmin;
  $("#categoryForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),name=String(f.get("name")||"").trim(),payload={slug:c.slug||name.toLowerCase().replace(/\\s+/g,"-"),name,description:String(f.get("description")||"").trim(),icon:String(f.get("icon")||"◇").trim()||"◇",sort_order:+f.get("sortOrder")||1,active:f.has("visible")};let r=old?await supabase.from("menu_categories").update(payload).eq("id",old.dbId):await supabase.from("menu_categories").insert(payload);if(r.error)return toast("ذخیره دسته ناموفق بود: "+r.error.message);await loadSupabaseData();render();adminTab="categories";dashboard();toast("دسته ذخیره شد")};
}
function bindAdmin(){
  $("[data-tab]").forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;drawAdmin()});
  $("#newProduct")?.addEventListener("click",()=>formProduct());$("#newCategory")?.addEventListener("click",()=>formCategory());
  $("[data-edit]").forEach(b=>b.onclick=()=>formProduct(b.dataset.edit));$("[data-cat-edit]").forEach(b=>b.onclick=()=>formCategory(b.dataset.catEdit));
  $("[data-toggle]").forEach(b=>b.onclick=async()=>{const p=data.products.find(x=>x.id===b.dataset.toggle);if(!p)return;const v=!p.available,r=await supabase.from("products").update({available:v,active:v}).eq("id",p.dbId);if(r.error)return toast("تغییر وضعیت ناموفق بود: "+r.error.message);await loadSupabaseData();render();drawAdmin()});
  $("[data-cat-toggle]").forEach(b=>b.onclick=async()=>{const c=data.categories.find(x=>x.id===b.dataset.catToggle);if(!c)return;const v=!c.visible,r=await supabase.from("menu_categories").update({active:v}).eq("id",c.dbId);if(r.error)return toast("تغییر وضعیت ناموفق بود: "+r.error.message);await loadSupabaseData();render();drawAdmin()});
  $("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("این محصول حذف شود؟"))return;const p=data.products.find(x=>x.id===b.dataset.delete);if(!p)return;const r=await supabase.from("products").delete().eq("id",p.dbId);if(r.error)return toast("حذف ناموفق بود: "+r.error.message);await loadSupabaseData();render();drawAdmin()});
  $("#saveSettings")?.addEventListener("click",async()=>{const f=new FormData($("#settingsForm")),payload={cafe_name:String(f.get("cafeName")||"").trim(),menu_title:String(f.get("menuTitle")||"").trim(),menu_subtitle:String(f.get("menuSubtitle")||"").trim(),phone:String(f.get("phone")||"").trim(),instagram:String(f.get("instagram")||"").trim(),opening_hours:String(f.get("openingHours")||"").trim(),currency:String(f.get("currency")||"تومان").trim(),address:String(f.get("address")||"").trim()},r=await supabase.from("menu_settings").update(payload).eq("id",1);if(r.error)return toast("ذخیره تنظیمات ناموفق بود: "+r.error.message);await loadSupabaseData();render();toast("تنظیمات ذخیره شد")});
}
async function submitOrderToSupabase(f){
  const items=cart.map(i=>({i,p:data.products.find(x=>x.id===i.productId)})).filter(x=>x.p);
  const {data:orderId,error}=await supabase.rpc("place_order",{p_customer_name:String(f.get("name")||"").trim(),p_customer_email:"",p_items:items.map(x=>({id:Number(x.p.dbId||x.p.id),qty:x.i.qty})),p_customer_phone:String(f.get("phone")||"").trim(),p_table_number:String(f.get("table")||"").trim(),p_note:String(f.get("note")||"").trim()});
  if(error)throw error;return orderId;
}
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="در حال ورود...";const f=new FormData(e.target),username=String(f.get("username")||"").trim(),password=String(f.get("password")||""),email=username.includes("@")?username:ADMIN_EMAIL,{error}=await supabase.auth.signInWithPassword({email,password});if(error){$("#loginError").textContent="ورود ناموفق: نام کاربری یا رمز عبور صحیح نیست.";return}if(!await isDbAdmin()){await supabase.auth.signOut();$("#loginError").textContent="این حساب دسترسی مدیریت ندارد.";return}sessionStorage.setItem(AUTH,"1");dashboard()};
$("#checkoutForm").onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent="در حال ثبت سفارش...";try{const f=new FormData(e.target),orderId=await submitOrderToSupabase(f),items=cart.map(i=>({i,p:data.products.find(x=>x.id===i.productId)})).filter(x=>x.p),total=items.reduce((a,x)=>a+(x.p.discountPrice??x.p.price)*x.i.qty,0);$("#orderSummary").hidden=false;$("#orderSummary").innerHTML="<h4>سفارش ثبت شد</h4><p>کد سفارش: <strong>"+esc(orderId)+"</strong></p><p>مشتری: "+esc(f.get("name"))+" · تماس: "+esc(f.get("phone"))+" · میز: "+esc(f.get("table")||"—")+"</p>"+items.map(x=>'<div class="summary-row"><span>'+esc(x.p.name)+" × "+num(x.i.qty)+'</span><b>'+money((x.p.discountPrice??x.p.price)*x.i.qty)+"</b></div>").join("")+'<div class="summary-row"><strong>جمع کل</strong><strong>'+money(total)+"</strong></div>"+(f.get("note")?'<p class="order-note">یادداشت: '+esc(f.get("note"))+"</p>":"")+'<div class="notice">سفارش در سرور ثبت شد.</div>';cart=[];saveCart();renderCart()}catch(err){toast("ثبت سفارش ناموفق بود: "+(err?.message||"خطای نامشخص"))}finally{btn.disabled=false;btn.textContent="ثبت سفارش"}};
(async function initSupabase(){try{await loadSupabaseData();render();renderCart();toast("منو از Supabase بارگذاری شد")}catch(err){console.error(err);render();renderCart();toast("اتصال به Supabase برقرار نشد")}})();
